AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for uploading user profile images.
Resources:
  PostProfilePictureFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/post_profile_picture-1.0.jar
      Handler: com.revature.post_profile_image.ProfilePictureUploadHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::011217676466:policy/QwizzardUserProfileImageBucketPutAccess
        - arn:aws:iam::011217676466:policy/service-role/AWSLambdaBasicExecutionRole-0122a76b-db79-440d-a45b-862bd20cd7e0
        - arn:aws:iam::011217676466:policy/dynamodb-update-users-item